CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	google_id TEXT UNIQUE NOT NULL,
	email TEXT UNIQUE NOT NULL,
	role TEXT NOT NULL DEFAULT 'admin',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS oauth_states (
	state TEXT PRIMARY KEY,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sessions (
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	token TEXT UNIQUE NOT NULL,
	expires_at TIMESTAMPTZ NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS posts (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	slug TEXT UNIQUE NOT NULL,
	summary TEXT,
	markdown TEXT NOT NULL,
	status TEXT NOT NULL DEFAULT 'draft',
	published_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS albums (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	slug TEXT UNIQUE NOT NULL,
	description TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS images (
	id SERIAL PRIMARY KEY,
	s3_key TEXT UNIQUE NOT NULL,
	width INT,
	height INT,
	caption TEXT,
	alt_text TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS album_images (
	album_id INT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
	image_id INT NOT NULL REFERENCES images(id) ON DELETE CASCADE,
	sort_order INT NOT NULL DEFAULT 0,
	PRIMARY KEY (album_id, image_id)
);

CREATE TABLE IF NOT EXISTS post_album_links (
	post_id INT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
	album_id INT NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
	PRIMARY KEY (post_id, album_id)
);
