AWSTemplateFormatVersion: '2010-09-09'
Description: Frontend infrastructure with S3, CloudFront, and Origin Access Control

Parameters:
  FrontendBucketName:
    Type: String
    Description: Name of the S3 bucket for frontend assets
    Default: photo-gallery-frontend
  
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # S3 Bucket for frontend static assets
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FrontendBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ["*"]
            MaxAge: 3000

  # CloudFront Origin Access Control for secure S3 access
  FrontendCloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${FrontendBucketName}-oac-${Environment}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution for frontend delivery
  FrontendCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub "CloudFront distribution for ${FrontendBucketName}"
        Enabled: true
        HttpVersion: http2and3
        PriceClass: PriceClass_100
        Origins:
          - Id: S3-FrontendBucket
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt FrontendCloudFrontOAC.Id
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3-FrontendBucket
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf  # CORS-S3Origin
          ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd  # CORS-With-Preflight
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  # S3 Bucket Policy for CloudFront access only
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Join ["", [!GetAtt FrontendBucket.Arn, "/*"]]
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendCloudFrontDistribution}"
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !Join ["", [!GetAtt FrontendBucket.Arn, "/*"]]
              - !GetAtt FrontendBucket.Arn
            Condition:
              Bool:
                "aws:SecureTransport": "false"

Outputs:
  FrontendBucketName:
    Description: "S3 bucket name for frontend assets"
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "${FrontendBucketName}-BucketName"

  CloudFrontDomain:
    Description: "CloudFront distribution domain name for frontend"
    Value: !GetAtt FrontendCloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${FrontendBucketName}-CloudFrontDomain"

  CloudFrontDistributionId:
    Description: "CloudFront distribution ID"
    Value: !Ref FrontendCloudFrontDistribution
    Export:
      Name: !Sub "${FrontendBucketName}-CloudFrontDistributionId"

  WebsiteURL:
    Description: "Frontend website URL via CloudFront"
    Value: !Sub "https://${FrontendCloudFrontDistribution.DomainName}"

